### ISSUE TITLE
Permission denied when adding to global environment

### ISSUE THREAD

**Issue by TLipede** [Roger-luo/IonCLI.jl#23] opened 2020-08-12 19:42 UTC
Hi there - first off, thank you for this package! I've been wanting something like this for a while :) 

I've been coming up against an error whenever I try to install a package globally. 
For reference, I'm a Linux (Arch) user, and I've tried this with the Julia official binaries, the Arch package manager install and building from source. 

For a minimally working example, I run:

`ion add -g OhMyREPL`

and get the following:

```
   Updating registry at `~/.julia/registries/General`
  Resolving package versions...
ERROR: SystemError: opening file "/home/tlipede/.julia/packages/IonCLI/LDdGk/Project.toml": Permission denied
Stacktrace:
 [1] systemerror(::String, ::Int32; extrainfo::Nothing) at ./error.jl:168
 [2] #systemerror#48 at ./error.jl:167 [inlined]
 [3] systemerror at ./error.jl:167 [inlined]
 [4] open(::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Bool, append::Nothing) at ./iostream.jl:284
 [5] open(::Pkg.Types.var"#31#33"{Base.GenericIOBuffer{Array{UInt8,1}}}, ::String; kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:truncate,),Tuple{Bool}}}) at ./io.jl:323
 [6] write_project at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/project.jl:180 [inlined]
 [7] write_project(::Pkg.Types.Project, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/project.jl:175
 [8] write_project at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/project.jl:173 [inlined]
 [9] write_env(::Pkg.Types.EnvCache; update_undo::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:1366
 [10] write_env at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:1366 [inlined]
 [11] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUID,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1136
 [12] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:189
 [13] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:140
 [14] add(::Array{Pkg.Types.PackageSpec,1}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67
 [15] add(::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67
 [16] do_cmd!(::Pkg.REPLMode.Command, ::Pkg.REPLMode.MiniREPL) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:404
 [17] do_cmd(::Pkg.REPLMode.MiniREPL, ::String; do_rethrow::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:382
 [18] top-level scope at none:1
ERROR: LoadError: failed process: Process(`/home/tlipede/packages/julias/julia-1.5/bin/julia --compile=min -g1 --color=yes --startup-file=no -e 'using Pkg;pkg"add OhMyREPL"'`, ProcessExited(1)) [1]
```

Is this expected? My Julia installation doesn't live in a root-owned directory so I feel like sudo shouldn't be warranted here.

**Comment by Roger-luo** [comment] 2020-08-15 22:56
no, this is a bug. I can reproduce this.

I'm not sure about why yet, however. Since in a local environment, the program should be opening this very Project.toml too, but somehow that works.

**Comment by TLipede** [comment] 2020-09-02 15:31
@Roger-luo I think I understand the bug now. Would file a PR though I'm not sure whether it should be in Ion or Comonicon. 
At the moment Ion is trying to modify its own Manifest.toml and Project.toml, which are read-only (as is the case for any installed packages I guess). 
And that's because the default `JULIA_PROJECT` is set to `../.julia/packages/IonCLI/.../` here:
https://github.com/Roger-luo/Comonicon.jl/blob/dea3a678ac9341fb66b3d7cdbf47b3a561ad01e5/src/tools/build.jl#L412

I'm not sure whether I'm missing some context; is there a general reason that this is needed for other CLIs?

**Comment by Roger-luo** [comment] 2020-09-02 18:28
yes, it's the mechanism in Comonicon. Sorry I should have mentioned this here, I was trying to change this behaviour recently.

when adding packages `IonCLI` shouldn't change the environment of `IonCLI` itself (which may break the CLI application). I guess somehow when running `ion add -g` it runs inside the IonCLI's package environment.

What currently Comonicon does is that it will use the CLI package environment for the CLI, given CLIs are basically Applications, their dependencies should be fixed to corresponding version. However when I tried to commit `Manifest.toml` to the repo, the PackageCompiler generates unusable system image #24 on MacOS

I'm now thinking about letting Comonicon creats a shared environment for each application. So the `Manifest.toml` can be generated locally, since I'm still not sure why PackageCompiler fails on MacOS.

**Comment by Roger-luo** [comment] 2020-09-02 18:30
IonCLI will spawn a subsprocess that uses current environment or global shared environment (enabled by -g) https://github.com/Roger-luo/IonCLI.jl/blob/master/src/project.jl#L3

but I guess currently the environment variable `JULIA_PROJECT` was passed to the subprocess somehow.

**Comment by TLipede** [comment] 2020-09-03 00:00
> What currently Comonicon does is that it will use the CLI package environment for the CLI, given CLIs are basically Applications, their dependencies should be fixed to corresponding version. However when I tried to commit `Manifest.toml` to the repo, the PackageCompiler generates unusable system image #24 on MacOS
> 
> I'm now thinking about letting Comonicon creats a shared environment for each application. So the `Manifest.toml` can be generated locally, since I'm still not sure why PackageCompiler fails on MacOS.

Ahh thanks, that makes sense :)

> IonCLI will spawn a subsprocess that uses current environment or global shared environment (enabled by -g) https://github.com/Roger-luo/IonCLI.jl/blob/master/src/project.jl#L3
> 
> but I guess currently the environment variable `JULIA_PROJECT` was passed to the subprocess somehow.

I think this happens when the CLI executable gets built (just in case you haven't seen). E.g. my ion executable looks like:
```
#!/bin/sh
JULIA_PROJECT=/home/tlipede/.julia/packages/IonCLI/PHR6x /home/tlipede/.asdf/installs/julia/1.5.1/bin/julia \
    -J/home/tlipede/.julia/packages/IonCLI/PHR6x/deps/lib/libion.so \
    --compile=min \
    -O2 \
    -- /home/tlipede/.julia/bin/ion.jl $@
```
Which is why everything works as expected when using the REPL via `using IonCLI; IonCLI.update(; glob=true)`. I'm not sure if there is, but if a Julia function exists to grab the 'default' project then maybe that could be used in the `withenv` function when `glob==true`? Otherwise, if the inline environment variable could be removed just for this package then I think that would also work

**Comment by Roger-luo** [comment] 2020-09-03 01:05
I just figured out why. The subprocess will inherit `ENV` by default, but the main process is started using `JULIA_PROCESS` environment variable, and this is because a bug in julia compiler CLI.... (when both --project and -J are specified part of the options will not be parsed correctly)

I just fixed it in #27 .

**Comment by Roger-luo** [comment] 2020-09-03 01:20
I just merged that PR (and tagged a patch version), please try it again, let me know if it works or not. Note it you are on MacOS you need to build the system image yourself for now.

**Closed as completed** 2020-09-03 01:19 UTC
Labels: bug

**Comment by TLipede** [comment] 2020-09-03 16:07
Awesome thank you!
